# Generated by Django 3.2.7 on 2021-09-04 20:30

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('nohp', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('password', models.CharField(max_length=50)),
                ('dateJoin', models.DateTimeField(auto_now_add=True)),
                ('lastLogin', models.DateTimeField()),
            ],
        ),
    ]
